title: Alexandre Perrin
logo: assets/img/profile.png

description: >
  Engineering student at ENIB specialized in mechanical design,
  embedded systems and rapid prototyping.
  Passionate about aerospace, defense, autonomous systems
  and engineering innovation.

show_downloads: false

theme: jekyll-theme-cayman

lang: en
